### ISSUE TITLE
sendRequest using RDMA send or RDMA READ

### ISSUE THREAD

**Issue by djvulee** [accelio/JXIO#16]
the document and source code do not say anything about the RDMA method, if we want a high performance, can users using a RDMA Read instead of send?

**Comment by katyakats** [comment]
Hi!
Decision on whether to do RDMA read/write or send is an internal JXIO decision. JXIO chooses RDMA read/write for any packet larger than 512 bytes.
Katya

**Comment by djvulee** [comment]
Thanks,  I think maybe it is better to notice about this in the wiki? at my first glance, I thought JXIO only provide RDMA send/recv, because the API seem like this. And what's more


>An application developer can use the InputStream and OutputStream impl provided by the >JxioConnection classes to achieve RDMA send and receive from Java.

as write in https://github.com/accelio/JXIO/wiki/JxioConnection-Explained.

**Comment by rosenbaumalex** [comment]
I added the follow in several locations: "*JXIO maps the Java data
transfers commands to RDMA READ/WRITE operations when message size is
larger than 512 bytes. Else it will use RDMA SEND/RECV operations.*"

I updated the JXIO section here
<https://github.com/accelio/JXIO/wiki/Control-and-Data-Flows-Explained#msgpool-and-msg>
.
and the JxioConenction section here
<https://github.com/accelio/JXIO/wiki/JxioConnection-Explained#jxioconnection>
and
here
<https://github.com/accelio/JXIO/wiki/JxioConnection-Protocol-Explained#jxioconnection-data-flows>

thanks for the feedback
Alex


__________________________________
  Alex Rosenbaum  | +972-545-234-555
