### ISSUE TITLE
How to send a msg that don't expect response?

### ISSUE THREAD

**Issue by lynus** [accelio/JXIO#20]
Hello, I'm trying to reimplement Hadoop RPC with JXIO.
When the connection is setting up, client sends a header message to server. This message does not expect any responses. 
Normally, msg can  return to its pool, when the response arrives and processed. However, in my case, the msg won't get response(ie. no onResponse() callback happens to this msg), thus I wonder when I should call returnToParentPool() on the msg.

**Comment by katyakats** [comment]
Hi!
Unfortunately, in JXIO each request should be answered. I can suggest that the server will send a dummy response to solve this issue. 
Thanks,
Katya
